### PR TITLE
Ability to pass options to `git-branch` command

### PR DESCRIPTION
**Pull request by rstims**

### CODE REVIEW

**Comment by JPeer264** [comment]
Hey @rstims, thanks for your PR. Can you please remove the `package-lock.json`, as I am using yarn in this project. I will merge it then

**Comment by rstims** [comment]
@JPeer264 thanks, should be good to go, let me know if anything else needs to be fixed

**Comment by JPeer264** [comment]
Appveyor is actually failing on Node v4. But I am planning to remove the Node v4 support anyways the next release

**Comment by JPeer264** [comment]
@rstims your feature is available in v`1.1.0`

**Comment by rstims** [comment]
@JPeer264 awesome, thanks!

**Pull request merged**
